import L from"axios";import{S as b,i as w}from"./assets/vendor-B2mb6eXk.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const S="47661758-276cd75f39684298817518b5c",v="https://pixabay.com/api/";async function h(e,n=1,o=15){const s=new URLSearchParams({key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:o});try{return(await L.get(`${v}?${s}`)).data}catch(t){console.error(t)}}const m=document.querySelector(".loader-btn"),g=document.querySelector(".load-more");function p(e,n){const o=e.map(s=>q(s)).join("");n.insertAdjacentHTML("beforeend",o),lightbox?lightbox.refresh():lightbox=new b(".gallery a")}function q({webformatURL:e,largeImageURL:n,tags:o,likes:s,views:t,comments:r,downloads:a}){return`
    <a class="gallery-item" href="${n}">
      <img src="${e}" alt="${o}" loading="lazy" />
      <div class="info">
        <p><span>Likes:</span> ${s}</p>
        <p><span>Views:</span> ${t}</p>
        <p><span>Comments:</span> ${r}</p>
        <p><span>Downloads:</span> ${a}</p>
      </div>
    </a>
  `}function M(e){e.innerHTML=""}function c(e){w.error({message:e,messageColor:"#fff",position:"topRight",backgroundColor:"#5b8cd1"})}function B(){const e=document.createElement("div");e.className="loader",document.body.appendChild(e)}function u(){const e=document.querySelector(".loader");e&&document.body.removeChild(e)}function E(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}function P(){m.classList.remove("hidden")}function $(){m.classList.add("hidden")}const C=document.querySelector("form"),i=document.querySelector(".gallery"),O=document.querySelector(".load-more");let l="",d=1,f=0;C.addEventListener("submit",I);O.addEventListener("click",x);function I(e){if(e.preventDefault(),y(),M(i),l=e.currentTarget.elements.query.value.trim(),d=1,l===""){c("Please enter a search query.");return}B(),h(l,d).then(o=>{if(u(),o.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}f=o.totalHits,p(o.hits,i),o.hits.length<15||i.children.length>=f?showEndOfResultsMessage():E()}).catch(o=>{console.log(o),c("Failed to fetch images. Please try again later.")}),e.currentTarget.reset()}function x(){d+=1,P(),h(l,d).then(e=>{u(),p(e.hits,i),$(),i.children.length>=f&&(y(),showEndOfResultsMessage()),R()}).catch(e=>{u(),console.log(e),c("Failed to fetch images. Please try again later.")})}function R(){const{height:e}=i.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
